"""`sn book <t> <subject> <book-code> [<source>] [--offset N]` (plan 2.2, 3.2): a converted
textbook into `references/<subject>/<book-code>/` with a README table and the map.

With `<source>` (a doc-extract folder: `document.md`, `manifest.json`, `provenance.json`,
`figures/`): the files are copied (the original PDF/Office file stays out), a README is
written with the printed-page offset and a table made from the book's own table of contents,
and the map (`index.md`) is generated by the learner repo's `tools/book_index.py`. A writer
then checks the README table against the contents. Without `<source>`: only the map is
generated again from the (checked) README. `references/` is private; nothing is published.

The offset may be negative (sn 0.3.11): an excerpt whose PDF page 1 is printed page 5 has
`--offset -4` (or `--offset=-4`), and the README line `printed-page offset: -4` is read back by
`book_index.py`. The placed files are recorded as soon as they are all in place, the map only
when `book_index.py` succeeds: a failed map leaves a recorded book whose map is made again with
`sn book <t> <subject> <code>` once the README is fixed."""

import subprocess
import sys
from pathlib import Path

from ..sources.naming import slug
from ..sources.toolload import load_tool
from ..state import safefs
from . import tool_writes
from .common import Refused

ORIGINALS = (".pdf", ".pptx", ".ppt", ".docx", ".doc")


def readme(code: str, offset: int, rows) -> str:
    lines = [f"# {code}", "", f"printed-page offset: {offset}", "", "<!-- book-index: readme -->", "",
             "| Lecke vagy rész | Nyomtatott kezdőoldal |", "|---|---|"]
    lines += [f"| {name} | {start} |" for name, start, _ in rows if start is not None]
    return "\n".join(lines) + "\n"


def place(repo: Path, rel: str, source: Path, code: str, offset: int) -> list[str]:
    if safefs.exists(repo, rel):
        raise Refused(f"{rel} már létezik; a térkép újragenerálása: sn book <tanuló> <tantárgy> <kód>")
    if not (source / "document.md").is_file():
        raise Refused(f"{source}: nincs document.md (doc-extract mappa kell)")
    written = []
    for path in sorted(p for p in source.rglob("*") if p.is_file()):
        if path.suffix.lower() in ORIGINALS:
            continue
        target = f"{rel}/{path.relative_to(source).as_posix()}"
        safefs.copy_in(path, repo, target)
        written.append(target)
    if not safefs.is_file(repo, f"{rel}/README.md"):
        tool = load_tool("book_index", repo / "tools")
        rows = tool.toc_rows(safefs.read_text(repo, f"{rel}/document.md").split("\n"))
        safefs.write_text(repo, f"{rel}/README.md", readme(code, offset, rows))
        written.append(f"{rel}/README.md")
    return written


def run(local, subject: str, code: str, source: Path | None, offset: int | None) -> int:
    repo = local.repo
    rel = f"references/{slug(subject)}/{slug(code)}"
    if source is not None:
        if offset is None:
            raise Refused("új könyvhöz kell az --offset N (nyomtatott oldal = PDF-oldal - N)")
        written = place(repo, rel, source, code, offset)
        tool_writes.record(repo, files=written)      # all copied: the guard knows them even if the map fails
        print(f"elhelyezve: {rel} ({len(written)} fájl)")
    elif not safefs.is_file(repo, f"{rel}/README.md"):
        raise Refused(f"{rel}/README.md nincs meg")
    else:
        written = []
    # one token, so a negative offset is never read as an option
    argv = [sys.executable, "tools/book_index.py", rel] + ([f"--offset={offset}"] if offset is not None and source is None else [])
    proc = subprocess.run(argv, cwd=repo, capture_output=True, text=True, timeout=300)
    print(proc.stdout.strip() or proc.stderr.strip())
    if proc.returncode == 0:      # the writer guard accepts exactly what this run wrote
        tool_writes.record(repo, files=written + [f"{rel}/index.md"])
    elif source is not None:
        print(f"Hiba: a térkép nem készült el; a könyv elhelyezve és rögzítve ({rel}). A README javítása után: "
              f"sn book <tanuló> {subject} {code} (forrásmappa nélkül)")
    local.record("book", "ok" if proc.returncode == 0 else "error", target=rel)
    return proc.returncode
